---
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'


stages:
  - build
  - test
  - release
  # - deploy
  - notify

build-frontend-code-job:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - docker build --build-arg VERSION=$VERSION --tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA


sonarqube-frontend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_USER_HOME: ${CI_PROJECT_DIR}/frontend/.sonar
  script:
    - cd frontend
    - mkdir -p .sonar/cashe
    - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY_FRONT -Dsonar.sources=.
      -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONAR_LOGIN_FRONTEND -Dsonar.projectName="21_EduardYurchikhin_frontend"
  artifacts:
    paths:
      - frontend/.sonar
      - frontend/.sonar/cashe
  cache:
    paths:
      - frontend/.sonar/cashe
  needs:
    - build-frontend-code-job

upload-frontend-release:
  stage: release
  image: docker:20.10.12-dind-rootless
  needs:
    - build-frontend-code-job
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd frontend
    - docker pull $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/sausage-frontend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/sausage-frontend:latest
    - docker push $CI_REGISTRY_IMAGE/sausage-frontend:latest

# deploy:
#   stage: deploy
#   before_script:
#     #устанавливаем ssh-agent для удобства аутентификации по ssh
#     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     #сохраняем сгенеренный ранее приватный ключ для раннера
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 600 ~/.ssh
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#     - scp ./docker-compose.yml ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/docker-compose.yml
#   script:
#     - ssh ${DEV_USER}@${DEV_HOST} "export "VERSION=${VERSION}"; export "SPRING_DATASOURCE_URL=${PSQL_DATASOURCE}"; export "SPRING_DATASOURCE_USERNAME=${PSQL_ADMIN}"; export "SPRING_DATASOURCE_PASSWORD=${PSQL_PASSWORD}"; export "SPRING_DATA_MONGODB_URI=${MONGO_DATA}";setsid /bin/bash -s " < ./frontend/docker_compose_front_deploy.sh
#   environment:
#     name: frontend
#     url: http://std-021-09.praktikum-services.tech/#


telegram-notification-frontend:
  stage: notify
  only:
    changes:
      - frontend/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\":
      \"-1001626584285\", \"text\": \"Эдуард Юрчихин собрал Front скачать можно
      тут
      $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-frontend-code-job.\"
      }"
      "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"'
  needs:
    - build-frontend-code-job
