version: '3.4'

services:
  backend-blue:
    image: gitlab.praktikum-services.ru:5050/std-021-009/sausage-store/sausage-backend:latest
    container_name: sausage-backend-blue
    healthcheck:
      test: curl –fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 20s
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: myproxy
    networks:
      - sausage-store

  backend-green:
    image: gitlab.praktikum-services.ru:5050/std-021-009/sausage-store/sausage-backend:latest
    container_name: sausage-backend-green
    restart: always
    healthcheck:
      test: curl –fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 20s
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: myproxy
    networks:
      - sausage-store

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-021-009/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    restart: always
    environment:
      DB: ${SPRING_DATA_MONGODB_URI}
    networks:
      - sausage-store

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-021-009/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: myproxy
    networks:
      - sausage-store

networks:
  sausage-store:
    driver: bridge
