---
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/backend/.m2/repository
  JAVA_OPTS: -XX:MaxRAMPercentage=90

stages:
  - build
  - test
  - release
  - notify
  # - deploy

include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

build-backend-code-job:
  stage: build
  image: docker:20.10.12-dind-rootless
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend
    - docker build --build-arg VERSION=$VERSION --tag $CI_REGISTRY_IMAGE/sausage-backend:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE/sausage-backend:$CI_COMMIT_SHA


sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    SONAR_USER_HOME: ${CI_PROJECT_DIR}/backend/.sonar
  script:
    - cd backend
    - mkdir -p .sonar/cache
    - mvn verify sonar:sonar -Dsonar.host.url=$SONARQUBE_URL
      -Dsonar.projectKey=$SONAR_PROJECT_KEY_BACK
      -Dsonar.login=$SONAR_LOGIN_BACKEND -Dsonar.qualitygate.wait=true
      -Dsonar.projectName="21_EduardYurchikhin_backend"
  artifacts:
    paths:
      - backend/.sonar
      - backend/.sonar/cache
  cache:
    paths:
      - backend/.sonar/cache
  needs:
    - build-backend-code-job

upload-backend-release:
  stage: release
  image: docker:20.10.12-dind-rootless
  needs:
    - build-backend-code-job
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd backend
    - docker pull $CI_REGISTRY_IMAGE/sausage-backend:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE/sausage-backend:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/sausage-backend:latest
    - docker push $CI_REGISTRY_IMAGE/sausage-backend:latest


# deploy:
#   stage: deploy
#   image: vault:1.13.3
#   before_script:
#     - apk add openssh-client bash
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 600 ~/.ssh
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#     - scp ./docker-compose.yml ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/docker-compose.yml
#   script:
#   - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=sausage-store jwt=$CI_JOB_JWT)"
#   - ssh ${DEV_USER}@${DEV_HOST} "export "VERSION=${VERSION}"; export "SPRING_DATASOURCE_URL=$(vault kv get -field=spring.datasource.url secret/sausage-store)"; export "SPRING_DATASOURCE_USERNAME=$(vault kv get -field=spring.datasource.username secret/sausage-store)"; export "SPRING_DATASOURCE_PASSWORD=$(vault kv get -field=spring.datasource.password secret/sausage-store)";setsid /bin/bash -s " < ./backend/docker_compose_deploy.sh
#   environment:
#     name: backend
#     url: http://std-021-09.praktikum-services.tech/#


telegram-notification-backend:
  stage: notify
  only:
    changes:
      - backend/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl -X POST -H "Content-type: application/json" --data "{\"chat_id\":
      \"-1001626584285\", \"text\": \"Эдуард Юрчихин собрал Back скачать можно
      тут
      $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job.\"
      }"
      "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage"'
  needs:
    - build-backend-code-job
